import datetime

rasp_a = [
    [{"name": "Физ-ра",
      "week": 0,
      "start": datetime.time(hour=8,minute=0),
      "end": datetime.time(hour=9,minute=30),
      "class": "4 корпус",
      "teacher": "-"},

     {"name": "Матан (лекц)",
      "week": 0,
      "start": datetime.time(hour=9,minute=50),
      "end": datetime.time(hour=11,minute=20),
      "class": "3308",
      "teacher": "Солнышкин Сергей Николаевич"},

     {"name": "Дискретная математика (пр)",
      "week": 0,
      "start": datetime.time(hour=11,minute=40),
      "end": datetime.time(hour=13,minute=10),
      "class": "2114",
      "teacher": "Чухнов Антон Сергеевич"}],

    [{"name": "Экономика (пр)",
      "week": 2,
      "start": datetime.time(hour=11,minute=40),
      "end": datetime.time(hour=13,minute=10),
      "class": "3426",
      "teacher": "Заставенко Екатерина Валерьевна"},

     {"name": "АиГ (лекц)",
      "week": 0,
      "start": datetime.time(hour=13,minute=45),
      "end": datetime.time(hour=15,minute=15),
      "class": "3308",
      "teacher": "Зельвенский Игорь Григорьевич"},

     {"name": "Матан (пр)",
      "week": 0,
      "start": datetime.time(hour=15,minute=35),
      "end": datetime.time(hour=17,minute=5),
      "class": "3313",
      "teacher": "Коточигов Александр Михайлович"},

     {"name": "АиГ (лекц)",
      "week": 0,
      "start": datetime.time(hour=17,minute=25),
      "end": datetime.time(hour=18,minute=55),
      "class": "3428",
      "teacher": "Зельвенский Игорь Григорьевич"}],

    [{"name": "Экономика (лекц)",
      "week": 1,
      "start": datetime.time(hour=8,minute=0),
      "end": datetime.time(hour=9,minute=30),
      "class": "5405",
      "teacher": "Ягья Талие Саидовна"},

     {"name": "Англ.яз.",
      "week": 0,
      "start": datetime.time(hour=9,minute=55),
      "end": datetime.time(hour=11,minute=20),
      "class": "каф. Ин.яз",
      "teacher": "-"},

     {"name": "Физика (лекц)",
      "week": 0,
      "start": datetime.time(hour=11,minute=40),
      "end": datetime.time(hour=13,minute=10),
      "class": "3107",
      "teacher": "Шейнман Илья Львович"},

     {"name": "Физ-ра",
      "week": 0,
      "start": datetime.time(hour=13,minute=45),
      "end": datetime.time(hour=15,minute=15),
      "class": "4 корпус",
      "teacher": "-"}],

    [{"name": "История (лекц)",
      "week": 1,
      "start": datetime.time(hour=13,minute=45),
      "end": datetime.time(hour=15,minute=15),
      "class": "5423",
      "teacher": "Меньшиков Дмитрий Никитович"},

     {"name": "Физ-ра",
      "week": 2,
      "start": datetime.time(hour=13,minute=45),
      "end": datetime.time(hour=15,minute=15),
      "class": "4 корпус",
      "teacher": "-"},

     {"name": "Программирование (лекц)",
      "week": 0,
      "start": datetime.time(hour=15,minute=35),
      "end": datetime.time(hour=17,minute=5),
      "class": "5405",
      "teacher": "Самойленко Владимир Петрович"},

     {"name": "Программирование",
      "week": 0,
      "start": datetime.time(hour=17,minute=25),
      "end": datetime.time(hour=18,minute=55),
      "class": "3402",
      "teacher": "Самойленко Владимир Петрович"}],

    [],

    [{"name": "История",
      "week": 0,
      "start": datetime.time(hour=11,minute=40),
      "end": datetime.time(hour=13,minute=10),
      "class": "3417",
      "teacher": "Стогов Дмитрий Игоревич"},

     {"name": "Дискретная математика (лекц)",
      "week": 0,
      "start": datetime.time(hour=13,minute=45),
      "end": datetime.time(hour=15,minute=15),
      "class": "3308",
      "teacher": "Рыбин Сергей Витальевич"},

     {"name": "Физика (пр)",
      "week": 1,
      "start": datetime.time(hour=15,minute=35),
      "end": datetime.time(hour=17,minute=5),
      "class": "3107",
      "teacher": "Морозов Вениамин Васильевич"},

     {"name": "Физика (лаб)",
      "week": 2,
      "start": datetime.time(hour=15,minute=35),
      "end": datetime.time(hour=17,minute=5),
      "class": "каф. Физики",
      "teacher": "Иманбаева Райхан Талгатовна, Демидов Юрий Андреевич"}],

    []

]
